# Generated by Django 5.1.6 on 2025-08-11 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_truck_activated_truck_activation_payment'),
        ('payment', '0002_withdrawalmethod_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('booking', 'Booking'), ('truck_activation', 'Truck Activation')], default='booking', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='booking.truck'),
        ),
    ]
