# Generated by Django 5.1.6 on 2025-06-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_truck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truckimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='truckimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
