# Generated by Django 5.1.6 on 2025-08-11 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_truckimage_options_truckimage_order'),
        ('payment', '0002_withdrawalmethod_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truck',
            name='activation_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_truck', to='payment.payment'),
        ),
    ]
