# Generated by Django 5.1.6 on 2025-08-11 09:03

from django.db import migrations
def set_initial_activation_status(apps, schema_editor):
    Truck = apps.get_model('booking', 'Truck')
    # Set activated=True for existing trucks that are already available
    Truck.objects.filter(available=True).update(activated=True)
    # Set activated=False for others
    Truck.objects.filter(available=False).update(activated=False)


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_truck_activated_truck_activation_payment'),
    ]

    operations = [
        migrations.RunPython(set_initial_activation_status),
    ]
