# Generated by Django 5.1.6 on 2025-08-14 07:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20250811_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
