# Generated by Django 5.1.6 on 2025-11-09 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_truckimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_trucks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='truck',
            name='activation_method',
            field=models.CharField(blank=True, choices=[('payment', 'Payment Activation'), ('manual', 'Manual Activation')], max_length=10, null=True),
        ),
    ]
